# Generated by Django 4.2.6 on 2023-10-28 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteroupa', '0003_category_item_subcategory_order_item_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 35, 18, 688953, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 18, 35, 18, 690007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/siteroupa/images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteroupa.item')),
            ],
        ),
    ]
